version: '3'

services:
    tareas:
      build: servidor-gestor-tarea
      mem_limit: 512m
      ports:
      - "8080:8080"
      environment:
        SERVER_PORT: 8080
      restart: always
      




